name: Docker Build & Scan

on:
  workflow_call:
    outputs:
      image-tag:
        description: "Docker image tag"
        value: ${{ jobs.docker.outputs.image-tag }}
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        id: build
        run: |
          SANITIZED_REF_NAME=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          SHORT_SHA=${GITHUB_SHA::8}
          IMAGE_TAG="${SANITIZED_REF_NAME}-${SHORT_SHA}"
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/streamlit-app:${IMAGE_TAG}"

          echo "Building Docker image ${IMAGE_NAME}..."
          docker build -t streamlit-app:latest .

          docker tag streamlit-app:latest $IMAGE_NAME
          docker push $IMAGE_NAME

          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Docker image security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: streamlit-app:latest
          format: table